#!/usr/bin/env bash
#Bash script that installs HAProxy & makes configurations

apt-get -y install software-properties-common
add-apt-repository ppa:vbernat/haproxy-1.8
apt-get update
apt-get -y install haproxy
echo "ENABLED=1" >> /etc/default/haproxy
printf %s "listen  5405-webs
    bind *:80
    mode http
    balance roundrobin
    server 5405-web-01 54.91.184.60:80 check
    server 5405-web-02 54.242.122.135:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
